print('Witaj, świecie!')
print('Jak masz na imię?')
myName = input()
print('Miło Cię poznać, ' + myName + '.')
print('Liczba znaków w twoim imieniu wynosi: ')
print(len(myName))
print('Ile masz lat ?')
myAge = input()
print('Za rok będziesz miał ' + str(int(myAge) + 1) + ' lat.')
print()
print(round(2.9821,3))